# /etc/portage/make.conf - consult /usr/share/portage/config/make.conf.example

CC="clang"
CXX="clang++"
LD="ld.lld"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
STRIP="llvm-strip"
OBJCOPY="llvm-objcopy"
OBJDUMP="llvm-objdump"
READELF="llvm-readelf"

COMMON_FLAGS="-O3 -pipe -march=native -flto=thin" # runtimes are already defined at /etc/clang/gentoo-runtimes.cfg
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
# FCFLAGS="-O3 -pipe -march=native" # enabling [-flto=thin] causes -> configure: error: cannot compile a simple Fortran program
# FFLAGS="${FCFLAGS}"
RUSTFLAGS="-C target-cpu=native -C link-arg=-Wl,-z,pack-relative-relocs -C opt-level=2" # enable target-cpu=native and DT_RELR (reduces size of compiled binaries). opt-level is similar to Clang's optimization options

LDFLAGS="-Wl,-O2 -Wl,--as-needed"  # -O2 in LDFLAGS refers to binary size optimization during linking, it is NOT related to the -O levels of the compiler

CMAKE_MAKEFILE_GENERATOR=ninja
MAKEOPTS="-j8 -l10.8"

EMERGE_DEFAULT_OPTS="--ask --deep --tree --verbose --load-average 10.8 --jobs 2" # -l: 12(cores)*0.9 = 10.8 / -j: 2*8=16 [16 gb, recommended 2gb per job. compiling 1 pckg -> 1gb x job. compiling 2 pckgs -> 2gb x job]
FEATURES="parallel-install userfetch candy clean-logs parallel-fetch"

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

PORTAGE_ELOG_CLASSES="log warn error info qa"
PORTAGE_ELOG_SYSTEM="save"
PORTAGE_LOGDIR="/var/log/portage"

ACCEPT_LICENSE="*"
USE="bluetooth cjk clang -latex llvm-libunwind lto 
     nvenc opus pipewire pgo pulseaudio vaapi verify-sig 
     vulkan xinerama -accessibility -cdinstall -cdr -dvd -dvdr 
     -emacs -geoip -geolocation -gnome -gnome-keyring -gps -gtk-doc -kde -networkmanager -nls 
     -nouveau -plasma -policykit -systemd -telemetry -vala -vdpau -vim-syntax -vnc -xscreensaver" 

CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3"
INPUT_DEVICES="libinput"
VIDEO_CARDS="intel nvidia"

LC_MESSAGES=C
L10N="es-ES es en-US en ca ja"

GRUB_PLATFORMS="efi-64"
GENTOO_MIRRORS="http://ftp.belnet.be/pub/rsync.gentoo.org/gentoo/ http://www.mirrorservice.org/sites/distfiles.gentoo.org/ http://mirrors.soeasyto.com/distfiles.gentoo.org/"
# http://gentoo.mirrors.ovh.net/gentoo-distfiles/
